/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module aluLogic_3 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg overflow,
    output reg [7:0] aluOUT,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [8-1:0] M_add_out;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_n;
  wire [1-1:0] M_add_overflow;
  reg [8-1:0] M_add_a;
  reg [8-1:0] M_add_b;
  reg [6-1:0] M_add_alufn;
  aluADD_9 add (
    .a(M_add_a),
    .b(M_add_b),
    .alufn(M_add_alufn),
    .out(M_add_out),
    .z(M_add_z),
    .v(M_add_v),
    .n(M_add_n),
    .overflow(M_add_overflow)
  );
  
  wire [8-1:0] M_bool_out;
  reg [8-1:0] M_bool_a;
  reg [8-1:0] M_bool_b;
  reg [6-1:0] M_bool_alufn;
  aluBOOL_10 bool (
    .a(M_bool_a),
    .b(M_bool_b),
    .alufn(M_bool_alufn),
    .out(M_bool_out)
  );
  
  wire [8-1:0] M_comp_out;
  reg [6-1:0] M_comp_alufn;
  reg [1-1:0] M_comp_z;
  reg [1-1:0] M_comp_n;
  reg [1-1:0] M_comp_v;
  aluCOMP_11 comp (
    .alufn(M_comp_alufn),
    .z(M_comp_z),
    .n(M_comp_n),
    .v(M_comp_v),
    .out(M_comp_out)
  );
  
  wire [8-1:0] M_shift_out;
  reg [8-1:0] M_shift_a;
  reg [8-1:0] M_shift_b;
  reg [6-1:0] M_shift_alufn;
  aluSHIFT_12 shift (
    .a(M_shift_a),
    .b(M_shift_b),
    .alufn(M_shift_alufn),
    .out(M_shift_out)
  );
  
  always @* begin
    M_add_a = a;
    M_add_b = b;
    M_add_alufn = alufn;
    M_bool_a = a;
    M_bool_b = b;
    M_bool_alufn = alufn;
    M_comp_z = M_add_z;
    M_comp_v = M_add_v;
    M_comp_n = M_add_n;
    M_comp_alufn = alufn;
    M_shift_a = a;
    M_shift_b = b;
    M_shift_alufn = alufn;
    
    case (alufn[4+1-:2])
      2'h0: begin
        aluOUT = M_add_out;
      end
      2'h1: begin
        aluOUT = M_bool_out;
      end
      2'h2: begin
        aluOUT = M_shift_out;
      end
      2'h3: begin
        aluOUT = M_comp_out;
      end
      default: begin
        aluOUT = 8'h00;
      end
    endcase
    overflow = M_add_overflow;
    z = M_add_z;
    v = M_add_v;
    n = M_add_n;
  end
endmodule
