/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module aluLogic_6 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg overflow,
    output reg [7:0] aluOUT,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [8-1:0] M_add_out;
  wire [1-1:0] M_add_z;
  wire [1-1:0] M_add_v;
  wire [1-1:0] M_add_n;
  wire [1-1:0] M_add_overflow;
  reg [8-1:0] M_add_a;
  reg [8-1:0] M_add_b;
  reg [6-1:0] M_add_alufn;
  aluADD_11 add (
    .a(M_add_a),
    .b(M_add_b),
    .alufn(M_add_alufn),
    .out(M_add_out),
    .z(M_add_z),
    .v(M_add_v),
    .n(M_add_n),
    .overflow(M_add_overflow)
  );
  
  always @* begin
    M_add_a = a;
    M_add_b = b;
    M_add_alufn = alufn;
    
    case (alufn[4+1-:2])
      2'h0: begin
        aluOUT = M_add_out;
      end
      default: begin
        aluOUT = 8'h00;
      end
    endcase
    overflow = M_add_overflow;
    z = M_add_z;
    v = M_add_v;
    n = M_add_n;
  end
endmodule
